// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC721TokenReceiver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC721TokenReceiver";
  readonly sourceName: "contracts/gbm/interfaces/IERC721TokenReceiver.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_operator","type":"address"},{"internalType":"address","name":"_from","type":"address"},{"internalType":"uint256","name":"_tokenId","type":"uint256"},{"internalType":"bytes","name":"_data","type":"bytes"}],"name":"onERC721Received","outputs":[{"internalType":"bytes4","name":"","type":"bytes4"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/gbm/interfaces/IERC721TokenReceiver.sol";
  readonly buildInfoId: "solc-0_8_20-b85f9cfe4cab07e9559623a9ebaedd8f56f2ba7b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC721TokenReceiver"]: IERC721TokenReceiver$Type;
    ["contracts/gbm/interfaces/IERC721TokenReceiver.sol:IERC721TokenReceiver"]: IERC721TokenReceiver$Type;
  }
}