// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Ownable$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Ownable";
  readonly sourceName: "contracts/gbm/interfaces/Ownable.sol";
  readonly abi: [{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/gbm/interfaces/Ownable.sol";
  readonly buildInfoId: "solc-0_8_20-6f2bb91fe730bdfdfde5b1a672c80169b7927823";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Ownable"]: Ownable$Type;
    ["contracts/gbm/interfaces/Ownable.sol:Ownable"]: Ownable$Type;
  }
}