// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Modifiers$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Modifiers";
  readonly sourceName: "contracts/gbm/libraries/AppStorage.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220bdf38a0ff0ff02cc23dfe34d80841624aa2be5deb2a09285364bba882eaeda4864736f6c63430008140033";
  readonly deployedBytecode: "0x60806040525f80fdfea2646970667358221220bdf38a0ff0ff02cc23dfe34d80841624aa2be5deb2a09285364bba882eaeda4864736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/gbm/libraries/AppStorage.sol";
  readonly buildInfoId: "solc-0_8_20-1574317a237f9f866699426b19da269855c2de91";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Modifiers"]: Modifiers$Type;
    ["contracts/gbm/libraries/AppStorage.sol:Modifiers"]: Modifiers$Type;
  }
}