// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface LibSignature$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "LibSignature";
  readonly sourceName: "contracts/gbm/libraries/LibSignature.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220da9347721d54173d13f5132fa91c649f7434615f86ac9b88b52e5b026001d55c64736f6c63430008140033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220da9347721d54173d13f5132fa91c649f7434615f86ac9b88b52e5b026001d55c64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/gbm/libraries/LibSignature.sol";
  readonly buildInfoId: "solc-0_8_20-b85f9cfe4cab07e9559623a9ebaedd8f56f2ba7b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["LibSignature"]: LibSignature$Type;
    ["contracts/gbm/libraries/LibSignature.sol:LibSignature"]: LibSignature$Type;
  }
}