// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Modifiers$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Modifiers";
  readonly sourceName: "contracts/gbm/libraries/AppStorage.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea26469706673582212204a897fb59925fc0af206fa66c248d22a318dc216631de574d29e7eea3bd911ad64736f6c63430008140033";
  readonly deployedBytecode: "0x60806040525f80fdfea26469706673582212204a897fb59925fc0af206fa66c248d22a318dc216631de574d29e7eea3bd911ad64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/gbm/libraries/AppStorage.sol";
  readonly buildInfoId: "solc-0_8_20-6f2bb91fe730bdfdfde5b1a672c80169b7927823";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Modifiers"]: Modifiers$Type;
    ["contracts/gbm/libraries/AppStorage.sol:Modifiers"]: Modifiers$Type;
  }
}