// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Modifiers$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Modifiers";
  readonly sourceName: "contracts/gbm/libraries/AppStorage.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220159332da62ed978ea3a58f748bce4754653cb3d2e0ca50d09c66328cb69f9ae564736f6c63430008140033";
  readonly deployedBytecode: "0x60806040525f80fdfea2646970667358221220159332da62ed978ea3a58f748bce4754653cb3d2e0ca50d09c66328cb69f9ae564736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/gbm/libraries/AppStorage.sol";
  readonly buildInfoId: "solc-0_8_20-b85f9cfe4cab07e9559623a9ebaedd8f56f2ba7b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Modifiers"]: Modifiers$Type;
    ["contracts/gbm/libraries/AppStorage.sol:Modifiers"]: Modifiers$Type;
  }
}